# let's install all required R packages

install.packages(c('devtools','curl'), dependencies=T)
library(devtools)
devtools::install_github("matthewjdenny/SpeedReader", dependencies=T) 
install.packages("tm") 
install.packages("jsonlite")
install.packages("slam") 
install.packages("igraph") 
install.packages("stringr") 
install.packages("cluster") 
install.packages("cmaes") 
install.packages("snakecase") 
install.packages("stopwords") 
install.packages("NMOF")
install.packages("xtable") 
install.packages("Matrix") 
install.packages("GA")  
install.packages("slam")  
install.packages("DEoptim")  
install.packages("GenSA")  
install.packages("metaheuristicOpt")  
install.packages("randomsearch")  
install.packages("parma")  
install.packages("pracma")  
install.packages("philentropy")  
install.packages('topicmodels', dependencies=T)  
install.packages('textmineR')
install.packages('corpus', dependencies = T)

